main: com.Guayand0.MineBank
name: MineBank
version: 5.5.3
author: Guayand0
api-version: 1.13
folia-supported: true
description: This plugin adds a money bank.

depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - Essentials

commands:
  minebank:
    description: Initial command
    usage: /minebank <arg0>
    aliases: mb
  bank:
    description: Bank Command
    usage: /bank <arg0> [<arg1> <arg2> ...]

permissions:
  minebank.admin:
    default: op
    description: Used to unlock admin commands
  minebank.migration:
    default: op
    description: Allows you to migrate plugin data to other database systems
  minebank.backup:
    default: op
    description: Allows you to backup plugin data
  minebank.updatechecker:
    default: op
    description: Allows you to receive a message if there is a plugin update
  minebank.use:
    default: op
    description: Allows you to use the player plugin commands
