# ############################################################################################################# #
# +-----------------------------------------------------------------------------------------------------------+ #
# |                                                                                                           | #
# |                      ███╗   ███╗██╗███╗  ██╗███████╗██████╗  █████╗ ███╗  ██╗██╗  ██╗                     | #
# |                      ████╗ ████║██║████╗ ██║██╔════╝██╔══██╗██╔══██╗████╗ ██║██║ ██╔╝                     | #
# |                      ██╔████╔██║██║██╔██╗██║█████╗  ██████╦╝███████║██╔██╗██║█████═╝                      | #
# |                      ██║╚██╔╝██║██║██║╚████║██╔══╝  ██╔══██╗██╔══██║██║╚████║██╔═██╗                      | #
# |                      ██║ ╚═╝ ██║██║██║ ╚███║███████╗██████╦╝██║  ██║██║ ╚███║██║ ╚██╗                     | #
# |                      ╚═╝     ╚═╝╚═╝╚═╝  ╚══╝╚══════╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚══╝╚═╝  ╚═╝                     | #
# |                                                                                                           | #
# |                    Youtube:    www.youtube.com/@davigamer1614                                             | #
# |                    Github:     https://github.com/Guayand0/Minecraft-Plugin-MineBank                      | #
# |                                                                                                           | #
# +-----------------------------------------------------------------------------------------------------------+ #
# ############################################################################################################# #

# ############################################################################################################# #
# +-----------------------------------------------------------------------------------------------------------+ #
# |                                                                                                           | #
# |                                █████╗  █████╗ ███╗  ██╗███████╗██╗ ██████╗                                | #
# |                               ██╔══██╗██╔══██╗████╗ ██║██╔════╝██║██╔════╝                                | #
# |                               ██║  ╚═╝██║  ██║██╔██╗██║█████╗  ██║██║  ██╗                                | #
# |                               ██║  ██╗██║  ██║██║╚████║██╔══╝  ██║██║  ╚██╗                               | #
# |                               ╚█████╔╝╚█████╔╝██║ ╚███║██║     ██║╚██████╔╝                               | #
# |                                ╚════╝  ╚════╝ ╚═╝  ╚══╝╚═╝     ╚═╝ ╚═════╝                                | #
# |                                                                                                           | #
# +-----------------------------------------------------------------------------------------------------------+ #
# ############################################################################################################# #

config:

  # You can add a new language adding (language.yml) to lang folder
  # If you want to have support for more languages by default, send
  # the .yml file with the translations and the language via github
  # https://github.com/Guayand0/Minecraft-Plugin-MineBank/issues

  # Available default languages: en, es, fr, pt, it, ge, ru, ja, ko, zhcn
  # English - en.yml    # Portuguese - pt.yml   # Russian - ru.yml    # Simplified Chinese - zhcn.yml
  # Spanish - es.yml    # Italian - it.yml      # Japanese - ja.yml
  # French - fr.yml     # German - ge.yml       # Korean - ko.yml
  message-language: en
  inventory-language: en

  # Enable/Disable the bank function
  bank-use: true

  # Enable/Disable the new version available message (update-message)
  update-checker: true

# ############################################################################################################# #
# +-----------------------------------------------------------------------------------------------------------+ #
# |                                                                                                           | #
# |              ██████╗  █████╗ ███╗  ██╗██╗  ██╗   █████╗  █████╗ ███╗  ██╗███████╗██╗ ██████╗              | #
# |              ██╔══██╗██╔══██╗████╗ ██║██║ ██╔╝  ██╔══██╗██╔══██╗████╗ ██║██╔════╝██║██╔════╝              | #
# |              ██████╦╝███████║██╔██╗██║█████═╝   ██║  ╚═╝██║  ██║██╔██╗██║█████╗  ██║██║  ██╗              | #
# |              ██╔══██╗██╔══██║██║╚████║██╔═██╗   ██║  ██╗██║  ██║██║╚████║██╔══╝  ██║██║  ╚██╗             | #
# |              ██████╦╝██║  ██║██║ ╚███║██║ ╚██╗  ╚█████╔╝╚█████╔╝██║ ╚███║██║     ██║╚██████╔╝             | #
# |              ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚══╝╚═╝  ╚═╝   ╚════╝  ╚════╝ ╚═╝  ╚══╝╚═╝     ╚═╝ ╚═════╝              | #
# |                                                                                                           | #
# +-----------------------------------------------------------------------------------------------------------+ #
# ############################################################################################################# #

bank:

  level:
    # MaxStorageAmount;UnlockNextLevelPrice
    1: 5000;2500
    2: 10000;5000
    3: 20000;10000
    4: 50000;25000
    5: 100000;50000
    # You can add and remove levels if you want

  profit:
    interval: 300 # Interval in seconds to receive profit (set -1 to disable) (you need to use "/mb reload" to apply)
    min-amount-to-win: 500 # Min amount of money in the bank to receive profit
    keep-in-bank: 1 # Percentage of profit for having money in the bank
  interests:
    min-amount-to-lose: 100 # Min amount of money withdraw to the bank to start rest interest (set -1 to disable)
    withdraw: 2 # Percentage of interest in withdraw money