main: mb.Guayando.MineBank
name: MineBank
version: 4.0.2
author: Guayando
api-version: 1.13
depend: [Vault]
softdepend: [PlaceholderAPI]
description: Un plugin que añade un banco de dinero.

commands:
  minebank:
    description: Comando principal
    usage: /minebank <arg0>
    aliases: mb
  bank:
    description: Comando del banco
    usage: /bank <arg0> [<arg1> <arg2> ...]

permissions:
  minebank.admin:
    default: op
    description: Sirve para poder usar comandos de administrador
  minebank.updatechecker:
    default: op
    description: Sirve para comprobar si hay una nueva version del plugin
  minebank.use:
    default: op
    description: Sirve para poder usar el banco